# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ======================
# METADATA SECTION
# ======================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sakura
  labels:
    app: sakura

# ======================
# SPEC SECTION
# ======================
spec:
  serviceName: sakura-tls-service
  replicas: {{ .Values.sakura.replica_count }}

  # ======================
  # SELECTOR SECTION
  # ======================
  selector:
    matchLabels:
      app: sakura

  # ======================
  # TEMPLATE SECTION
  # ======================
  template:
    metadata:
      labels:
        app: sakura
    spec:

      # ======================
      # AFFINITY SECTION
      # ======================
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sakura-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sakura
            topologyKey: kubernetes.io/hostname

      # ======================
      # INIT CONTAINERS SECTION
      # ======================
      initContainers:
      - name: copy-config
        image: busybox
        command:
          - sh
          - -c
          - |
            ORDINAL=${HOSTNAME##*-}
            mkdir -p /etc/ainari
            ls /configs
            cp /configs/sakura-config-${ORDINAL}/sakura.toml /etc/ainari/sakura.toml
        volumeMounts:
        - name: sakura-configs
          mountPath: /configs
        - name: sakura-config
          mountPath: /etc/ainari

      # ======================
      # CONTAINERS SECTION
      # ======================
      containers:
      # Sakura container
      - name: sakura
        image: {{ .Values.sakura.docker.repository }}:{{ .Values.sakura.docker.tag }}
        imagePullPolicy: {{ .Values.sakura.docker.pull_policy }}
        env:
        - name: RUST_LOG
          value: "debug,h2=info"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key
        - name: SAKURA_REGISTRATION_KEY
          valueFrom:
            secretKeyRef:
              name: sakura-registration-key
              key: sakura_retistration_key
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/sakura/
        - name: sakura-config
          mountPath: /etc/ainari
        - name: wg-secret
          mountPath: /etc/wireguard
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        readinessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:11420/v1alpha/is_ready
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:11420/v1alpha/is_ready
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3

      # TLS termination container
      - name: tls-termination
        image: nginx:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
        - name: sakura-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      # ======================
      # VOLUMES SECTION
      # ======================
      volumes:
        - name: sakura-configs
          projected:
            sources:
            {{- range $i := until (.Values.sakura.replica_count | int) }}
            - configMap:
                name: sakura-config-{{ $i }}
                items:
                - key: sakura.toml
                  path: sakura-config-{{ $i }}/sakura.toml
            {{- end }}
        - name: sakura-config
          emptyDir: {}
        - name: tls-certs
          secret:
            secretName: sakura-selfsigned-secret
        - name: sakura-nginx-config
          configMap:
            name: sakura-nginx-config
        - name: wg-secret
          secret:
            secretName: wg-sakura-secret

  # ======================
  # VOLUME CLAIM TEMPLATES SECTION
  # ======================
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.sakura.storage.storage_class }}
      resources:
        requests:
          storage: 100Mi
