# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $root := . }}
{{- $replicas := int .Values.sakura.replica_count }}
{{- range $i := until $replicas }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sakura-config-{{ $i }}
data:
  sakura.toml: |+
    debug = true
    log_path = ""
    skip_tls_verification = true
    address = "https://sakura-{{ $i }}.sakura-tls-service.{{ $root.Release.Namespace }}.svc.cluster.local:8443"

    [processing]
    max_number_of_threads = {{ $root.Values.sakura.processing.max_number_of_threads }}

    [storage]
    tempfile_location = "/tmp/sakura"

    [api]
    public_ip = "127.0.0.1"
    public_port = 11420
    internal_ip = "127.0.0.1"
    internal_port = 10420

    [database]
    file_path = "/etc/ainari/sakura/sakura_db"
    
    [miko]
    address = "https://miko-tls-service.{{ $root.Release.Namespace }}.svc.cluster.local:8443"
---  {{/* This separator is mandatory inside the loop. otherwise only one instance is created */}}
{{- end }}
