apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omamori-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storage_class }}
  resources:
    requests:
      storage: 100Mi
