apiVersion: v1
kind: Service
metadata:
  name: omamori-tls-service
  labels:
    run: omamori
spec:
  selector:
    app: omamori
  ports:
    - name: input
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
