apiVersion: v1
metadata:
  name: omamori-config
data:
  omamori.toml: |+
    debug = true
    log_path = ""
    insecure_clients = true

    [api]
    public_ip = "127.0.0.1"
    public_port = 11421
    internal_ip = "127.0.0.1"
    internal_port = 10421
    internal_api_key = "{{ .Values.api.internal_api_key }}"

    [database]
    file_path = "/etc/ainari/omamori/omamori_db"
    
    [miko]
    address = "https://miko-tls-service.default.svc.cluster.local:8443"

    [simple_crypto]
    key_b64 = "q9vN4CjOQm5wKzyzjZtS7t4oQp8oQK1JvU5xgq8vFzE="

kind: ConfigMap
