# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: omamori
  labels:
    app: omamori
spec:
  replicas: {{ .Values.omamori.replica_count }}
  selector:
    matchLabels:
      app: omamori
  template:
    metadata:
      labels:
        app: omamori
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: omamori-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - omamori
            topologyKey: kubernetes.io/hostname
      containers:
      - name: omamori
        image: {{ .Values.omamori.docker.repository }}:{{ .Values.omamori.docker.tag }}
        imagePullPolicy: {{ .Values.omamori.docker.pull_policy }}
        env:
        - name: RUST_LOG
          value: "debug"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/omamori/
        - name: omamori-config
          mountPath: /etc/ainari/omamori.toml
          subPath: omamori.toml
          readOnly: true
        readinessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:10421/v1alpha/is_ready
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:10421/v1alpha/is_ready
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3

      - name: tls-termination
        image: nginx:latest
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
        - name: omamori-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
        - name: omamori-config
          configMap:
            name: omamori-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: omamori-pvc
        - name: tls-certs
          secret:
            secretName: omamori-selfsigned-secret
        - name: omamori-nginx-config
          configMap:
            name: omamori-nginx-config
