apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omamori-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.api.domain_omamori }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omamori-tls-service
            port:
              number: 8443
