apiVersion: apps/v1
kind: Deployment
metadata:
  name: onsen
  labels:
    app: onsen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onsen
  template:
    metadata:
      labels:
        app: onsen
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: onsen-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onsen
            topologyKey: kubernetes.io/hostname
      containers:
      - name: onsen
        image: {{ .Values.docker.registry }}/onsen:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        env:
        - name: RUST_LOG
          value: "debug,h2=info"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key
        - name: ONSEN_REGISTRATION_KEY
          valueFrom:
            secretKeyRef:
              name: onsen-registration-key
              key: onsen_retistration_key
        ports:
        - containerPort: 50051
          name: grpc
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/onsen/
        - name: onsen-config
          mountPath: /etc/ainari/onsen.toml
          subPath: onsen.toml
          readOnly: true
        - name: wg-secret
          mountPath: /etc/wireguard
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE

      volumes:
        - name: onsen-config
          configMap:
            name: onsen-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: onsen-pvc
        - name: wg-secret
          secret:
            secretName: wg-onsen-secret
