# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: onsen
  labels:
    app: onsen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onsen
  template:
    metadata:
      labels:
        app: onsen
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: onsen-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onsen
            topologyKey: kubernetes.io/hostname
      containers:
      - name: onsen
        image: {{ .Values.onsen.docker.repository }}:{{ .Values.onsen.docker.tag }}
        imagePullPolicy: {{ .Values.onsen.docker.pull_policy }}
        env:
        - name: RUST_LOG
          value: "debug,h2=info"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key
        - name: ONSEN_REGISTRATION_KEY
          valueFrom:
            secretKeyRef:
              name: onsen-registration-key
              key: onsen_retistration_key
        ports:
        - containerPort: 50051
          name: grpc
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/onsen/
        - name: onsen-config
          mountPath: /etc/ainari/onsen.toml
          subPath: onsen.toml
          readOnly: true
        - name: wg-secret
          mountPath: /etc/wireguard
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE

      volumes:
        - name: onsen-config
          configMap:
            name: onsen-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: onsen-pvc
        - name: wg-secret
          secret:
            secretName: wg-onsen-secret
