# more than 1 replica is currently not supported
replicaCount: 1

user:
  id: ""
  name: ""
  passphrase: ""

token:
  data: ""
  expire_time: 3600

docker:
  tag: "develop"
  registry: "kitsudaiki"

api:
  domain_sakura: local-sakura
  domain_miko: local-miko
  domain_bento: local-bento
  domain_torii: local-torii
  domain_hanami: local-hanami
  domain_omamori: local-omamori
  internal_api_key: "dummy-key"

hanami:
  registation_key: "test-registration-key"

torii:
  service:
    type: LoadBalancer
  portRange:
    start: 10040
    end: 10050

processing:
  max_number_of_threads: 0

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
