# more than 1 replica is currently not supported
replicaCount: 1

user:
  id: ""
  name: ""
  passphrase: ""

token:
  data: ""
  expire_time: 3600

docker:
  tag: "develop"
  registry: "kitsudaiki"

api:
  domain_hanami: local-hanami
  domain_miko: local-miko
  domain_bento: local-bento

processing:
  max_number_of_threads: 0

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
