// Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub mod image;
pub mod onsen_host;

use uuid::Uuid;

use crate::config;

use ainari_api::common_functions::*;
use ainari_api::errors::ErrorResponse;
use ainari_api_structs::user_context::UserContext;
use ainari_clients::endpoints::get_endpoints;
use ainari_clients::secret::{generate_secret, get_secret_payload};
use ainari_common::secret::Secret;

/// Creates a new secret in the omamori, which is used to encrypt the files of an image.
///
/// Every image gets its own key. The key is generated by the omamori and read back directly
/// afterwards, because the ryokan needs the payload itself to encrypt the files, while only the
/// uuid of the secret is stored together with the image.
///
/// # Arguments
///
/// * `image_uuid` - Uuid of the image, which is used to build the name of the secret
/// * `context` - User-context of the request
///
/// # Returns
///
/// * `Ok((Uuid, Secret))` - Uuid of the new secret together with its payload.
/// * `Err(ErrorResponse)` - The endpoints, the omamori or the payload were not reachable.
async fn generate_new_key(
    image_uuid: &Uuid,
    context: &UserContext,
) -> Result<(Uuid, Secret), ErrorResponse> {
    let miko_endpoint = &config::CONFIG.miko;
    let endpoints = get_endpoints(miko_endpoint, config::CONFIG.skip_tls_verification)
        .await
        .map_err(map_ainari_error_to_api_response)?;
    let secret_name = format!("autogenerated secret for image {image_uuid}");

    let secret_meta = generate_secret(
        &endpoints.omamori,
        &context.token,
        &secret_name,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    let secret_payload = get_secret_payload(
        &endpoints.omamori,
        &context.token,
        &secret_meta.uuid,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    Ok((
        secret_meta.uuid,
        Secret::from(secret_payload.secret_payload),
    ))
}
