// Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use uuid::Uuid;

use crate::config;

use ainari_api::common_functions::*;
use ainari_api::errors::ErrorResponse;
use ainari_api_structs::user_context::UserContext;
use ainari_clients::endpoints::get_endpoints;
use ainari_clients::secret::{clone_secret, generate_secret, get_secret_payload};
use ainari_common::config::Endpoint;
use ainari_common::secret::Secret;

pub mod image;
pub mod onsen_host;
pub mod project;

/// Returns the endpoint of the omamori, requested from the miko.
async fn get_omamori_endpoint() -> Result<Endpoint, ErrorResponse> {
    let miko_endpoint = &config::CONFIG.miko;
    let endpoints = get_endpoints(miko_endpoint, config::CONFIG.skip_tls_verification)
        .await
        .map_err(map_ainari_error_to_api_response)?;
    Ok(endpoints.omamori)
}

/// Creates a new secret in the omamori, which is used to encrypt the files of an image.
///
/// Every image gets its own key. The key is generated by the omamori and read back directly
/// afterwards, because the ryokan needs the payload itself to encrypt the files, while only the
/// uuid of the secret is stored together with the image.
///
/// # Arguments
///
/// * `image_uuid` - Uuid of the image, which is used to build the name of the secret
/// * `context` - User-context of the request
///
/// # Returns
///
/// * `Ok((Uuid, Secret))` - Uuid of the new secret together with its payload.
/// * `Err(ErrorResponse)` - The endpoints, the omamori or the payload were not reachable.
async fn generate_new_key(
    image_uuid: &Uuid,
    owned_by: &str,
    resource_uuid: &Uuid,
    context: &UserContext,
) -> Result<(Uuid, Secret), ErrorResponse> {
    let omamori_endpoint = get_omamori_endpoint().await?;
    let secret_name = format!("autogenerated secret for image {image_uuid}");

    let secret_meta = generate_secret(
        &omamori_endpoint,
        &context.token,
        &config::INTERNAL_API_KEY,
        &secret_name,
        owned_by,
        resource_uuid,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    let secret = get_secret_payload(
        &omamori_endpoint,
        &context.token,
        &secret_meta.uuid,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    Ok((secret_meta.uuid, secret))
}

/// Clones an already existing secret, which was provided by the user to encrypt the files of an
/// image, and reads the payload of the clone from the omamori.
///
/// The clone is owned by the resource, so it can be deleted together with the resource, while the
/// secret of the user stays untouched.
///
/// # Arguments
///
/// * `secret_uuid` - Uuid of the existing secret
/// * `owned_by` - Kind of the resource, which owns the clone
/// * `resource_uuid` - Uuid of the resource, which owns the clone
/// * `context` - User-context of the request
///
/// # Returns
///
/// * `Ok((Uuid, Secret))` - Uuid of the cloned secret and its payload.
/// * `Err(ErrorResponse)` - The endpoints or the omamori were not reachable, or the secret doesn't
///   exist or is not accessible for the user.
async fn get_existing_key(
    secret_uuid: &Uuid,
    owned_by: &str,
    resource_uuid: &Uuid,
    context: &UserContext,
) -> Result<(Uuid, Secret), ErrorResponse> {
    let omamori_endpoint = get_omamori_endpoint().await?;
    let cloned_secret = clone_secret(
        &omamori_endpoint,
        &context.token,
        &config::INTERNAL_API_KEY,
        secret_uuid,
        owned_by,
        resource_uuid,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    let secret_payload = get_secret_payload(
        &omamori_endpoint,
        &context.token,
        &cloned_secret.uuid,
        config::CONFIG.skip_tls_verification,
    )
    .await
    .map_err(map_ainari_error_to_api_response)?;

    Ok((cloned_secret.uuid, secret_payload))
}
