//go:build !ignore_autogenerated

// Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ainari) DeepCopyInto(out *Ainari) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ainari.
func (in *Ainari) DeepCopy() *Ainari {
	if in == nil {
		return nil
	}
	out := new(Ainari)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ainari) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AinariList) DeepCopyInto(out *AinariList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ainari, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AinariList.
func (in *AinariList) DeepCopy() *AinariList {
	if in == nil {
		return nil
	}
	out := new(AinariList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AinariList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AinariSpec) DeepCopyInto(out *AinariSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	in.MySQL.DeepCopyInto(&out.MySQL)
	out.Miko = in.Miko
	out.Hanami = in.Hanami
	out.Sakura = in.Sakura
	out.Ryokan = in.Ryokan
	out.Omamori = in.Omamori
	out.Izakaya = in.Izakaya
	in.Onsen.DeepCopyInto(&out.Onsen)
	in.Torii.DeepCopyInto(&out.Torii)
	out.Dashboard = in.Dashboard
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AinariSpec.
func (in *AinariSpec) DeepCopy() *AinariSpec {
	if in == nil {
		return nil
	}
	out := new(AinariSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AinariStatus) DeepCopyInto(out *AinariStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AinariStatus.
func (in *AinariStatus) DeepCopy() *AinariStatus {
	if in == nil {
		return nil
	}
	out := new(AinariStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatesSpec) DeepCopyInto(out *CertificatesSpec) {
	*out = *in
	if in.ExtraDNSNames != nil {
		in, out := &in.ExtraDNSNames, &out.ExtraDNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraIPAddresses != nil {
		in, out := &in.ExtraIPAddresses, &out.ExtraIPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatesSpec.
func (in *CertificatesSpec) DeepCopy() *CertificatesSpec {
	if in == nil {
		return nil
	}
	out := new(CertificatesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServicesSpec) DeepCopyInto(out *ExternalServicesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServicesSpec.
func (in *ExternalServicesSpec) DeepCopy() *ExternalServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpec) DeepCopyInto(out *GlobalSpec) {
	*out = *in
	out.Ingress = in.Ingress
	in.Certificates.DeepCopyInto(&out.Certificates)
	out.WireGuard = in.WireGuard
	out.ExternalServices = in.ExternalServices
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpec.
func (in *GlobalSpec) DeepCopy() *GlobalSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HanamiNetworkSpec) DeepCopyInto(out *HanamiNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HanamiNetworkSpec.
func (in *HanamiNetworkSpec) DeepCopy() *HanamiNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(HanamiNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HanamiSpec) DeepCopyInto(out *HanamiSpec) {
	*out = *in
	out.Network = in.Network
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HanamiSpec.
func (in *HanamiSpec) DeepCopy() *HanamiSpec {
	if in == nil {
		return nil
	}
	out := new(HanamiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IzakayaSpec) DeepCopyInto(out *IzakayaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IzakayaSpec.
func (in *IzakayaSpec) DeepCopy() *IzakayaSpec {
	if in == nil {
		return nil
	}
	out := new(IzakayaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MikoAdminSpec) DeepCopyInto(out *MikoAdminSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MikoAdminSpec.
func (in *MikoAdminSpec) DeepCopy() *MikoAdminSpec {
	if in == nil {
		return nil
	}
	out := new(MikoAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MikoSpec) DeepCopyInto(out *MikoSpec) {
	*out = *in
	out.Admin = in.Admin
	out.Token = in.Token
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MikoSpec.
func (in *MikoSpec) DeepCopy() *MikoSpec {
	if in == nil {
		return nil
	}
	out := new(MikoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MikoTokenSpec) DeepCopyInto(out *MikoTokenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MikoTokenSpec.
func (in *MikoTokenSpec) DeepCopy() *MikoTokenSpec {
	if in == nil {
		return nil
	}
	out := new(MikoTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLDatabaseSpec) DeepCopyInto(out *MySQLDatabaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLDatabaseSpec.
func (in *MySQLDatabaseSpec) DeepCopy() *MySQLDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLDatabasesSpec) DeepCopyInto(out *MySQLDatabasesSpec) {
	*out = *in
	out.Miko = in.Miko
	out.Hanami = in.Hanami
	out.Ryokan = in.Ryokan
	out.Omamori = in.Omamori
	out.Izakaya = in.Izakaya
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLDatabasesSpec.
func (in *MySQLDatabasesSpec) DeepCopy() *MySQLDatabasesSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLDatabasesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLSpec) DeepCopyInto(out *MySQLSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
	out.Databases = in.Databases
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLSpec.
func (in *MySQLSpec) DeepCopy() *MySQLSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmamoriSpec) DeepCopyInto(out *OmamoriSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmamoriSpec.
func (in *OmamoriSpec) DeepCopy() *OmamoriSpec {
	if in == nil {
		return nil
	}
	out := new(OmamoriSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnsenSpec) DeepCopyInto(out *OnsenSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnsenSpec.
func (in *OnsenSpec) DeepCopy() *OnsenSpec {
	if in == nil {
		return nil
	}
	out := new(OnsenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRangeSpec) DeepCopyInto(out *PortRangeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRangeSpec.
func (in *PortRangeSpec) DeepCopy() *PortRangeSpec {
	if in == nil {
		return nil
	}
	out := new(PortRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RyokanSpec) DeepCopyInto(out *RyokanSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RyokanSpec.
func (in *RyokanSpec) DeepCopy() *RyokanSpec {
	if in == nil {
		return nil
	}
	out := new(RyokanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SakuraSpec) DeepCopyInto(out *SakuraSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SakuraSpec.
func (in *SakuraSpec) DeepCopy() *SakuraSpec {
	if in == nil {
		return nil
	}
	out := new(SakuraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToriiPublicSpec) DeepCopyInto(out *ToriiPublicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToriiPublicSpec.
func (in *ToriiPublicSpec) DeepCopy() *ToriiPublicSpec {
	if in == nil {
		return nil
	}
	out := new(ToriiPublicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToriiSpec) DeepCopyInto(out *ToriiSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
	out.PortRange = in.PortRange
	out.Public = in.Public
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToriiSpec.
func (in *ToriiSpec) DeepCopy() *ToriiSpec {
	if in == nil {
		return nil
	}
	out := new(ToriiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardSpec) DeepCopyInto(out *WireGuardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardSpec.
func (in *WireGuardSpec) DeepCopy() *WireGuardSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardSpec)
	in.DeepCopyInto(out)
	return out
}
