docker:
  tag: "local_test"
  pull_policy: "Never"

user:
  id: "asdf"
  name: "asdf"
  passphrase: "asdfasdf"

token:
  data: "this-is-a-test"

api:
  domain_sakura: local-vagrant-sakura
  domain_miko: local-vagrant-miko
  domain_ryokan: local-vagrant-ryokan
  domain_torii: local-vagrant-torii
  domain_hanami: local-vagrant-hanami
  domain_omamori: local-vagrant-omamori
  domain_onsen: local-vagrant-onsen
  domain_dashboard: local-vagrant-ainari
