apiVersion: v1
metadata:
  name: ryokan-config
data:
  ryokan.toml: |+
    debug = true
    log_path = ""
    skip_tls_verification = true

    [storage]
    tempfile_location = "/tmp/ryokan"

    [api]
    public_ip = "127.0.0.1"
    public_port = 11416
    internal_ip = "127.0.0.1"
    internal_port = 10416

    [database]
    file_path = "/etc/ainari/ryokan/ryokan_db"
    
    [miko]
    address = "https://miko-tls-service.default.svc.cluster.local:8443"

    [onsen]
    registation_key = "test-registration-key"

kind: ConfigMap
