apiVersion: v1
kind: PersistentVolume
metadata:
  name: ryokan-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ryokan-sc
  hostPath:
    path: /etc/ainari_data/
