apiVersion: v1
metadata:
  name: hanami-config
data:
  hanami.toml: |+
    debug = true
    log_path = ""

    [processing]
    max_number_of_threads = {{ .Values.processing.max_number_of_threads }}

    [api]
    ip = "127.0.0.1"
    port = 11418

    [database]
    file_path = "/etc/ainari/hanami/hanami_db"
    
    [miko]
    address = "https://miko-tls-service.default.svc.cluster.local"
    port = 8443
    insecure = true

    [bento]
    address = "https://bento-tls-service.default.svc.cluster.local"
    port = 8443
    insecure = true

kind: ConfigMap
