apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanami
  labels:
    app: hanami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanami
  template:
    metadata:
      labels:
        app: hanami
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hanami-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hanami
            topologyKey: kubernetes.io/hostname
      containers:
      - name: hanami
        image: {{ .Values.docker.registry }}/hanami:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        env:
        - name: RUST_LOG
          value: "debug"
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/hanami/
        - name: shared-vol
          mountPath: /etc/ainari/bento_data
        - name: hanami-config
          mountPath: /etc/ainari/hanami.toml
          subPath: hanami.toml
          readOnly: true

      - name: tls-termination
        image: nginx:latest
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
        - name: hanami-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
        - name: hanami-config
          configMap:
            name: hanami-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: hanami-pvc
        - name: tls-certs
          secret:
            secretName: hanami-selfsigned-secret
        - name: hanami-nginx-config
          configMap:
            name: hanami-nginx-config
        - name: shared-vol
          persistentVolumeClaim:
            claimName: shared-longhorn-pvc
