apiVersion: v1
metadata:
  name: hanami-config
data:
  hanami.toml: |+
    debug = true
    log_path = ""
    skip_tls_verification = true

    [api]
    public_ip = "127.0.0.1"
    public_port = 11418
    internal_ip = "127.0.0.1"
    internal_port = 10418

    [database]
    file_path = "/etc/ainari/hanami/hanami_db"
    
    [miko]
    address = "https://miko-tls-service.default.svc.cluster.local:8443"

kind: ConfigMap
