[package]
name = "torii-ebpf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
torii_common = { path = "../../libs/rust/torii_common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
network-types = "0.2.0" 

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "torii"
path = "src/main.rs"
