[package]
name = "ainari_common"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.1"

[dependencies]
# logging
log = "0.4"
env_logger = "0.11"

# common
chrono = { version = "0.4", features = ["serde"] }

# hash
sha2 = "0.11.0"
hex = "0.4"

# encoding
base64 = "0.23"

# json
serde = { version = "1", features = ["derive", "serde_derive", "alloc"] }
serde_json = "1"
schemars = { package = "apistos-schemars", version = "0.8", features = ["chrono", "uuid1", "url", "rust_decimal"] }
validator = { version = "0.21", features = ["derive"] }

# database-traits
diesel = { version = "2.3", features = ["sqlite"]}
uuid = { version = "1.23.1", features = ["v4"] }
