apiVersion: v1
kind: Service
metadata:
  name: bento-tls-service
  labels:
    run: bento
spec:
  selector:
    app: bento
  ports:
    - name: input
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
