apiVersion: v1
metadata:
  name: bento-config
data:
  bento.toml: |+
    debug = true
    log_path = ""
    insecure_clients = true

    [storage]
    dataset_location = "/etc/ainari/bento_data/datasets"
    checkpoint_location = "/etc/ainari/bento_data/checkpoints"
    tempfile_location = "/etc/ainari/bento_data/tempfiles"

    [api]
    public_ip = "127.0.0.1"
    public_port = 11416
    internal_ip = "127.0.0.1"
    internal_port = 10416
    internal_api_key = "{{ .Values.api.internal_api_key }}"

    [database]
    file_path = "/etc/ainari/bento/bento_db"
    
    [miko]
    address = "https://miko-tls-service.default.svc.cluster.local"
    port = 8443

kind: ConfigMap
