debug = true
log_path = "/var/log"
insecure_clients = true

[database]
file_path = "/etc/ainari/bento_db"

[storage]
dataset_location = "/etc/ainari/datasets"
checkpoint_location = "/etc/ainari/checkpoints"
tempfile_location = "/etc/ainari/tempfiles"
tempfile_timeout = 10

[api]
public_ip = "0.0.0.0"
public_port = 11416
internal_ip = "0.0.0.0"
internal_port = 10416
internal_api_key = "asdf"

[miko]
address = "http://127.0.0.1"
port = 11417

