debug = true
log_path = "/var/log"

[database]
file_path = "/etc/ainari/hanami_db"

[processing]
# 0 means there is no limitation
max_number_of_threads = 0

[api]
ip = "0.0.0.0"
port = 11418

[miko]
address = "http://127.0.0.1"
port = 11417
insecure = true

[bento]
address = "http://127.0.0.1"
port = 11416
insecure = true
