debug = true
log_path = ""

[storage]
dataset_location = "/etc/ainari/datasets"
checkpoint_location = "/etc/ainari/checkpoints"
tempfile_location = "/etc/ainari/tempfiles"

[processing]
# 0 means there is no limitation
max_number_of_threads = 0

[auth]
token_key_path = "/etc/ainari/token_key"
token_expire_time = 36000

[api]
ip = "0.0.0.0"
port = 11418

[database]
file_path = "/etc/ainari/ainari_db"
