debug = true
# "stdout" or "log_file", the log-file is written into log_path
log_type = "stdout"
log_path = "/var/log/"
skip_tls_verification = true
address = "http://127.0.0.1:50051"

[miko]
address = "http://127.0.0.1:11417"

[storage]
location = "/tmp/onsen"
