debug = true
log_path = "/var/log"
insecure_clients = true
address = "http://127.0.0.1:50051"

[api]
public_ip = "0.0.0.0"
public_port = 11422
internal_ip = "0.0.0.0"
internal_port = 10422
internal_api_key = "asdf"

[miko]
address = "http://127.0.0.1:11417"

[storage]
location = "/tmp/onsen"

[ryokan]
registation_key = "test-registration-key"
