debug = true
log_path = "/var/log"
skip_tls_verification = true
address = "http://127.0.0.1:50051"

[miko]
address = "http://127.0.0.1:11417"

[storage]
location = "/tmp/onsen"

[ryokan]
registation_key = "test-registration-key"
