debug = true
log_path = "/var/log"
skip_tls_verification = true
address = "http://127.0.0.1:11420"

[api]
public_ip = "0.0.0.0"
public_port = 11420
internal_ip = "0.0.0.0"
internal_port = 10420

[database]
file_path = "/etc/ainari/sakura_db"

[miko]
address = "http://127.0.0.1:11417"

[processing]
# 0 means there is no limitation
max_number_of_threads = 0

[storage]
tempfile_location = "/tmp/sakura"
