debug = true
log_path = "/var/log"
skip_tls_verification = true
address = "http://127.0.0.1:11420"

[api]
public_ip = "0.0.0.0"
public_port = 11420
internal_ip = "0.0.0.0"
internal_port = 10420

[database]
file_path = "/etc/ainari/sakura_db"

[miko]
address = "http://127.0.0.1:11417"

[processing]
# 0 means there is no limitation
max_number_of_threads = 0

[storage]
local_vm_storage_path = "/etc/ainari/virtual_machines"
tempfile_location = "/tmp/sakura"

[hypervisor]
# path of the cloud-hypervisor binary, which runs the virtual machines
binary_path = "/usr/local/bin/cloud-hypervisor"
# path of the firmware, which boots the virtual machines
firmware_path = "/usr/local/share/CLOUDHV.fd"
