FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706 AS builder

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && \
        apt-get install -y protobuf-compiler \
                           gcc \
                           curl \
                           pkg-config \
                           libssl-dev && \
     curl https://sh.rustup.rs -sSf | sh -s -- -y

COPY . .

RUN ~/.cargo/bin/cargo build --release -p onsen
RUN cp target/release/onsen /app/

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl \
                       libsqlite3-0 \
                       wireguard-tools \
                       iptables-persistent \
                       iproute2 && \
    apt-get clean autoclean &&\
    apt-get autoremove --yes

# horrible dirty workaround to prevent the error
# sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"
# when starting wireguard inside the pod. Didn't found a better solution so far... 
RUN sed -i '/src_valid_mark/d' /usr/bin/wg-quick

# onsen
COPY --from=builder /app/onsen /usr/bin/onsen
COPY dockerfiles/files/start_onsen.sh /start_onsen.sh
RUN chmod +x /start_onsen.sh

CMD ["/start_onsen.sh"]
