# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kitsudaiki/ainari_build_base:0.2.0@sha256:b11c3a334aae2ef1dd456917239ed82617d3473147035573c42ab72eb0c5eb15 AS builder

WORKDIR /app

COPY src src
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# also copy the git-directory, which is necessary for the version-information
COPY .git .git

RUN ~/.cargo/bin/cargo build --release
RUN cp target/release/hanami /app/
RUN cp target/release/miko /app/
RUN cp target/release/omamori /app/
RUN cp target/release/onsen /app/
RUN cp target/release/ryokan /app/
RUN cp target/release/sakura /app/
RUN cp target/release/torii /app/

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl \
                       libsqlite3-0 \
                       wireguard-tools \
                       iptables-persistent \
                       iproute2 && \
    apt-get clean autoclean && \
    apt-get autoremove --yes

# horrible dirty workaround to prevent the error
# sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"
# when starting wireguard inside the pod. Didn't found a better solution so far... 
RUN sed -i '/src_valid_mark/d' /usr/bin/wg-quick

# onsen
COPY --from=builder /app/onsen /usr/bin/onsen
COPY dockerfiles/files/start_onsen.sh /start_onsen.sh
RUN chmod +x /start_onsen.sh

CMD ["/start_onsen.sh"]
