# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kitsudaiki/ainari_build_base:0.2.0@sha256:763aad737f50a8774e1beacef80c3174de145301194e78ef505553111ac46107 AS builder

WORKDIR /app

COPY src src
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# also copy the git-directory, which is necessary for the version-information
COPY .git .git

RUN ~/.cargo/bin/cargo build --release
RUN cp target/release/hanami /app/
RUN cp target/release/miko /app/
RUN cp target/release/omamori /app/
RUN cp target/release/onsen /app/
RUN cp target/release/ryokan /app/
RUN cp target/release/sakura /app/
RUN cp target/release/torii /app/

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y curl openssl libsqlite3-0 && \
    apt-get clean autoclean &&\
    apt-get autoremove --yes

COPY --from=builder /app/hanami /usr/bin/hanami
RUN useradd -m ainari && \
    mkdir -p /etc/ainari && \
    chown ainari:ainari /etc/ainari && \
    chown ainari:ainari /usr/bin/hanami && \
    chmod +x /usr/bin/hanami

USER ainari
CMD [ "hanami" ]
