# Copyright 2022 Tobias Anker
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kitsudaiki/ainari_base:latest AS builder

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl \
                       libsqlite3-0 \
                       wireguard-tools \
                       iptables-persistent \
                       iproute2 && \
    apt-get clean autoclean && \
    apt-get autoremove --yes

# horrible dirty workaround to prevent the error
# sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"
# when starting wireguard inside the pod. Didn't found a better solution so far... 
RUN sed -i '/src_valid_mark/d' /usr/bin/wg-quick

# onsen
COPY --from=builder /app/onsen /usr/bin/onsen
COPY dockerfiles/files/start_onsen.sh /start_onsen.sh
RUN chmod +x /start_onsen.sh

CMD ["/start_onsen.sh"]
