# Copyright 2022 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kitsudaiki/ainari_build_base:0.1.0@sha256:13539b10d230e68d952276a39b8e930f0b1f7f6544c518ec6dc422cab64389a0

WORKDIR /app

COPY src src
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

RUN ~/.cargo/bin/cargo build --release
RUN cp target/release/hanami /app/
RUN cp target/release/miko /app/
RUN cp target/release/omamori /app/
RUN cp target/release/onsen /app/
RUN cp target/release/ryokan /app/
RUN cp target/release/sakura /app/
RUN cp target/release/torii /app/
