# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kitsudaiki/ainari_build_base:0.2.0@sha256:763aad737f50a8774e1beacef80c3174de145301194e78ef505553111ac46107 AS builder

WORKDIR /app

COPY src src
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# the version-endpoint reports this value, which is read at compile-time. The git-directory
# itself is not copied into the image, because .dockerignore excludes it.
ARG GIT_VERSION=unknown
ENV GIT_VERSION=$GIT_VERSION

# only this component is built, the other binaries of the workspace have their own image
RUN ~/.cargo/bin/cargo build --release -p sakura
RUN cp target/release/sakura /app/

# the hypervisor, which runs the virtual machines, and the firmware, which boots them
ARG CLOUD_HYPERVISOR_VERSION=v53.0
RUN curl -fSLo /app/cloud-hypervisor \
        https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/${CLOUD_HYPERVISOR_VERSION}/cloud-hypervisor-static && \
    chmod +x /app/cloud-hypervisor
RUN curl -fSLo /app/CLOUDHV.fd \
        https://github.com/cloud-hypervisor/edk2/releases/latest/download/CLOUDHV.fd

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

# qemu-utils provides qemu-img, which converts a downloaded image into the boot-disk of a virtual
# machine. cloud-image-utils provides cloud-localds, which builds the cloud-init seed-image.
# libcap2-bin provides setcap, which is only used while building this image.
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl \
                       curl \
                       libsqlite3-0 \
                       qemu-utils \
                       cloud-image-utils \
                       libcap2-bin \
                       wireguard-tools \
                       iptables-persistent \
                       iproute2 \
                       sudo && \
    apt-get clean autoclean &&\
    apt-get autoremove --yes

# horrible dirty workaround to prevent the error
# sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"
# when starting wireguard inside the pod. Didn't found a better solution so far...
RUN sed -i '/src_valid_mark/d' /usr/bin/wg-quick

# Create ainari user and set up directories
RUN useradd -m ainari

# Allow the user to creage the wireguard-connection
RUN echo "ainari ALL=(ALL) NOPASSWD: /usr/bin/wg-quick" >> /etc/sudoers

# The virtual machines are opened through /dev/kvm, which belongs to the group 'kvm' on the host.
# The id of that group differs between hosts, so it can be overwritten at build-time and the
# container gets the id of the host additionally over 'group_add' in the docker-compose-file.
ARG KVM_GID=993
RUN groupadd -g ${KVM_GID} kvm || groupmod -g ${KVM_GID} kvm && \
    usermod -aG kvm ainari

# sakura
COPY --from=builder /app/sakura /home/ainari/sakura
COPY dockerfiles/files/start_sakura.sh /home/ainari/start_sakura.sh
RUN mkdir -p /etc/ainari/virtual_machines && \
    chown -R ainari:ainari /etc/ainari && \
    chown ainari:ainari /home/ainari/sakura && \
    chown ainari:ainari /home/ainari/start_sakura.sh && \
    chmod +x /home/ainari/sakura /home/ainari/start_sakura.sh

# the hypervisor and its firmware. The paths are the defaults of the '[hypervisor]'-section of
# the config of sakura.
COPY --from=builder /app/cloud-hypervisor /usr/local/bin/cloud-hypervisor
COPY --from=builder /app/CLOUDHV.fd /usr/local/share/CLOUDHV.fd

# Attaching a virtual machine to an existing TAP-device is the only privileged operation of this
# container. The capability is given to the hypervisor-binary itself, so neither sakura nor the
# container need to run as root. The container still has to carry CAP_NET_ADMIN in its bounding
# set, which the docker-compose-file does with 'cap_add'.
RUN setcap cap_net_admin+ep /usr/local/bin/cloud-hypervisor

USER ainari
WORKDIR /home/ainari

CMD ["/home/ainari/start_sakura.sh"]
