FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706 AS builder

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && \
        apt-get install -y gcc \
                           curl \
                           wget \
                           pkg-config \
                           libssl-dev \
                           libsqlite3-dev
RUN wget https://static.rust-lang.org/rustup/archive/1.28.2/x86_64-unknown-linux-gnu/rustup-init && \
    chmod +x ./rustup-init && \
    ./rustup-init -y --no-modify-path

COPY . .

RUN ~/.cargo/bin/cargo build --release -p sakura
RUN cp target/release/sakura /app/

# ---------------------------------------------------

FROM debian:12.12-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y openssl libsqlite3-0 && \
    apt-get clean autoclean &&\
    apt-get autoremove --yes

# sakura
COPY --from=builder /app/sakura /usr/bin/sakura
CMD [ "sakura" ]
