apiVersion: v1
kind: Service
metadata:
  name: torii-gateway-service
spec:
  type: {{ default "LoadBalancer" .Values.torii.service.type }}
  selector:
    app: torii
  ports:
{{- $start := int .Values.torii.portRange.start }}
{{- $end   := int .Values.torii.portRange.end }}
{{- $ports := split " " (seq $start $end) }}
{{- range $p := $ports }}
  - name: p-{{ $p }}
    port: {{ $p | int }}
    targetPort: {{ $p | int }}
    protocol: TCP
{{- end }}
