apiVersion: v1
metadata:
  name: torii-config
data:
  torii.toml: |+
    debug = true
    log_path = ""

    [auth]
    token_key_path = "/etc/ainari/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [api]
    ip = "127.0.0.1"
    port = 11417

    [database]
    file_path = "/etc/ainari/data/torii_db"

kind: ConfigMap
