# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Access to the virtual machines over ssh with the key-pair, which is generated by the test.
"""

import os
import subprocess
import time

from .config import Config


class SshError(RuntimeError):
    pass


class Ssh:
    def __init__(self, config: Config, log=print):
        self.config = config
        self.log = log

    def check_netns(self):
        """
        Raises an error, if the configured network-namespace doesn't exist, because otherwise every
        ssh-command fails and the tests would only wait until their timeouts.
        """
        netns = self.config.ssh_netns
        if netns and not os.path.exists(os.path.join("/run/netns", netns)):
            raise SshError(f"network-namespace '{netns}' of AINARI_SSH_NETNS doesn't exist. Unset "
                           f"AINARI_SSH_NETNS, if the floating ip-addresses are reachable from "
                           f"the host directly.")

    def generate_key(self) -> str:
        """
        Generates a fresh ssh-key-pair and returns the public key in its one-line representation.
        """
        key_path = self.config.ssh_key_path
        for path in (key_path, f"{key_path}.pub"):
            if os.path.exists(path):
                os.remove(path)

        subprocess.run(["ssh-keygen", "-t", "ed25519", "-N", "", "-C", "ainari-local-stack-test",
                        "-f", key_path],
                       check=True,
                       stdout=subprocess.DEVNULL)

        with open(f"{key_path}.pub", "r", encoding="utf-8") as file_handle:
            return file_handle.read().strip()

    def refresh_sudo(self):
        """
        The ssh-commands capture their output, so a password-prompt of sudo would not be visible.
        Because of this, the credentials of sudo are requested in advance, if they are required.
        """
        if self.config.ssh_netns:
            subprocess.run(["sudo", "-v"], check=True)

    def command_prefix(self) -> list:
        if self.config.ssh_netns:
            return ["sudo", "-n", "ip", "netns", "exec", self.config.ssh_netns]
        return []

    def run(self, address: str, command: str, connect_timeout: int = 5,
            timeout: float = 120) -> str:
        """
        Runs a command in the virtual machine over ssh and returns its output.
        """
        ssh_command = self.command_prefix() + [
            "ssh",
            "-i", self.config.ssh_key_path,
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", f"ConnectTimeout={connect_timeout}",
            "-o", "BatchMode=yes",
            "-o", "LogLevel=ERROR",
            f"{self.config.vm_user}@{address}",
            command,
        ]
        try:
            result = subprocess.run(ssh_command, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired as error:
            raise SshError(f"'{command}' on {address} timed out after {timeout}s") from error
        if result.returncode != 0:
            raise SshError(f"'{command}' on {address} failed with exit-code {result.returncode}: "
                           f"{result.stderr.strip()}")

        return result.stdout.strip()

    def wait(self, address: str, command: str = "hostname", timeout: float = None,
             expect=None) -> str:
        """
        Waits until the virtual machine answers on ssh and returns the output of the command. If
        expect is given, it is also waited, until the output passes this check.
        """
        timeout = timeout or self.config.ssh_timeout
        start_time = time.time()
        end_time = start_time + timeout
        next_report = start_time + 30
        last_error = ""
        while time.time() < end_time:
            try:
                output = self.run(address, command, timeout=30)
                if expect is None or expect(output):
                    return output
                last_error = f"unexpected output: {output}"
            except SshError as error:
                last_error = str(error)
            if time.time() >= next_report:
                # the wait can take minutes, so it is shown, why it is still waiting
                self.log(f"still waiting for {address} after {time.time() - start_time:.0f}s: "
                         f"{last_error}")
                next_report = time.time() + 30
            time.sleep(5.0)

        raise TimeoutError(f"no ssh-access to '{address}' within {timeout}s: {last_error}")

    def is_reachable(self, address: str) -> bool:
        try:
            self.run(address, "true", connect_timeout=3, timeout=15)
            return True
        except SshError:
            return False

    def wait_unreachable(self, address: str, timeout: float = 120) -> None:
        end_time = time.time() + timeout
        while time.time() < end_time:
            if not self.is_reachable(address):
                return
            time.sleep(3.0)
        raise TimeoutError(f"'{address}' is still reachable over ssh after {timeout}s")

    def login_command(self, address: str) -> str:
        prefix = " ".join(self.command_prefix()).replace(" -n", "")
        prefix = f"{prefix} " if prefix else ""
        return f"{prefix}ssh -i {self.config.ssh_key_path} {self.config.vm_user}@{address}"
