# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ======================
# METADATA SECTION
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miko
  labels:
    app: miko

# ======================
# SPEC SECTION
# ======================
spec:
  replicas: {{ .Values.miko.replica_count }}

  # ======================
  # SELECTOR SECTION
  # ======================
  selector:
    matchLabels:
      app: miko

  # ======================
  # TEMPLATE SECTION
  # ======================
  template:
    metadata:
      labels:
        app: miko
    spec:

      # ======================
      # AFFINITY SECTION
      # ======================
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: miko-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - miko
            topologyKey: kubernetes.io/hostname

      # ======================
      # CONTAINERS SECTION
      # ======================
      containers:
      # Miko container
      - name: miko
        image: {{ .Values.miko.docker.repository }}:{{ .Values.miko.docker.tag }}
        imagePullPolicy: {{ .Values.miko.docker.pull_policy }}
        env:
        - name: AINARI_ADMIN_ID
          value: {{ required "user.id is required!" .Values.miko.user.id }}
        - name: AINARI_ADMIN_NAME
          value: {{ required "user.name is required!" .Values.miko.user.name }}
        - name: AINARI_ADMIN_PASSPHRASE
          value: {{ required "user.passphrase is required!" .Values.miko.user.passphrase }}
        - name: RUST_LOG
          value: "debug"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key

        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/miko/
        - name: miko-config
          mountPath: /etc/ainari/miko.toml
          subPath: miko.toml
          readOnly: true
        - name: token-key
          mountPath: /etc/ainari/token_key
          subPath: token-key
          readOnly: true

        readinessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:10417/v1alpha/is_ready
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3

        livenessProbe:
          exec:
            command:
            - curl
            - --fail
            - localhost:10417/v1alpha/is_ready
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3

      # TLS termination container
      - name: tls-termination
        image: nginx:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
        - name: miko-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      # ======================
      # VOLUMES SECTION
      # ======================
      volumes:
        - name: miko-config
          configMap:
            name: miko-config
        - name: token-key
          secret:
            secretName: token-key
        - name: data-volume
          persistentVolumeClaim:
            claimName: miko-pvc
        - name: tls-certs
          secret:
            secretName: miko-selfsigned-secret
        - name: miko-nginx-config
          configMap:
            name: miko-nginx-config
