apiVersion: v1
metadata:
  name: miko-config
data:
  miko.toml: |+
    debug = true
    log_path = ""

    [auth]
    token_key_path = "/etc/ainari/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [api]
    public_ip = "127.0.0.1"
    public_port = 11417
    internal_ip = "127.0.0.1"
    internal_port = 10417
    internal_api_key = "{{ .Values.api.internal_api_key }}"

    [database]
    file_path = "/etc/ainari/miko/miko_db"

    [endpoints.sakura]
    public_address = "https://local-sakura"
    public_port = 443
    internal_address = "https://sakura-tls-service.default.svc.cluster.local"
    internal_port = 8443

    [endpoints.bento]
    public_address = "https://local-bento"
    public_port = 443
    internal_address = "https://bento-tls-service.default.svc.cluster.local"
    internal_port = 8443

kind: ConfigMap
