apiVersion: apps/v1
kind: Deployment
metadata:
  name: miko
  labels:
    app: miko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miko
  template:
    metadata:
      labels:
        app: miko
    spec:
      containers:
      - name: miko
        image: {{ .Values.docker.registry }}/miko:{{ .Values.docker.tag }}
        imagePullPolicy: {{ .Values.docker.pull_policy }}
        env:
        - name: AINARI_ADMIN_ID
          value: {{ required "user.id is required!" .Values.user.id }}
        - name: AINARI_ADMIN_NAME
          value: {{ required "user.name is required!" .Values.user.name }}
        - name: AINARI_ADMIN_PASSPHRASE
          value: {{ required "user.passphrase is required!" .Values.user.passphrase }}
        - name: RUST_LOG
          value: "debug"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: internal-api-key
              key: internal_api_key
        volumeMounts:
        - name: data-volume
          mountPath: /etc/ainari/miko/
        - name: miko-config
          mountPath: /etc/ainari/miko.toml
          subPath: miko.toml
          readOnly: true
        - name: token-key
          mountPath: /etc/ainari/token_key
          subPath: token-key
          readOnly: true

      - name: tls-termination
        image: nginx:latest
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
        - name: miko-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
        - name: miko-config
          configMap:
            name: miko-config
        - name: token-key
          secret:
            secretName: token-key
        - name: data-volume
          persistentVolumeClaim:
            claimName: miko-pvc
        - name: tls-certs
          secret:
            secretName: miko-selfsigned-secret
        - name: miko-nginx-config
          configMap:
            name: miko-nginx-config
