// Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package render

import (
	"fmt"
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ainariv1alpha1 "github.com/kitsudaiki/ainari/deploy/operator/api/v1alpha1"
	"github.com/kitsudaiki/ainari/deploy/operator/internal/secrets"
)

// mysqlHost is the address of the mysql-server, which is either the service of the deployed
// server or the configured external one.
func (r *renderer) mysqlHost() string {
	if r.Spec.MySQL.Deploy {
		return fmt.Sprintf("mysql.%s.svc.cluster.local", r.Namespace)
	}
	return r.Spec.MySQL.Host
}

// database returns the database of a component on the mysql-server.
func (r *renderer) database(name string) ainariv1alpha1.ComponentDatabase {
	for _, database := range r.Spec.MySQL.Databases.ByComponent() {
		if database.Component == name {
			return database
		}
	}
	panic(fmt.Sprintf("component '%s' has no database", name))
}

// mysql returns the mysql-server, if it is deployed into the cluster. Its passwords are
// generated by the secrets-package.
func (r *renderer) mysql() ([]client.Object, error) {
	if !r.Spec.MySQL.Deploy {
		return nil, nil
	}

	initScript, err := r.execute("create-databases.sh", r)
	if err != nil {
		return nil, err
	}

	return []client.Object{
		configMap("mysql-init", map[string]string{"create-databases.sh": initScript}),
		&corev1.Service{
			ObjectMeta: metav1.ObjectMeta{Name: "mysql", Labels: appLabels("mysql")},
			Spec: corev1.ServiceSpec{
				Type:     corev1.ServiceTypeClusterIP,
				Selector: appLabels("mysql"),
				Ports:    []corev1.ServicePort{servicePort("mysql", r.Spec.MySQL.Port, 3306)},
			},
		},
		r.mysqlStatefulSet(),
	}, nil
}

// mysqlStatefulSet returns the mysql-server, which runs on the node with the label
// 'mysql-node=true'.
func (r *renderer) mysqlStatefulSet() *appsv1.StatefulSet {
	env := []corev1.EnvVar{envSecret("MYSQL_ROOT_PASSWORD", secrets.MySQLRootPassword)}
	// read by the init-script, which creates the users of the components
	for _, database := range r.Spec.MySQL.Databases.ByComponent() {
		name := database.Component
		env = append(env, envSecret(strings.ToUpper(name)+"_PASSWORD", secrets.MySQLPassword(&r.Spec.MySQL, name)))
	}

	ping := corev1.ProbeHandler{
		Exec: &corev1.ExecAction{
			Command: []string{"sh", "-c", "mysqladmin ping --host=127.0.0.1 --connect-timeout=2 > /dev/null 2>&1"},
		},
	}
	// The server only listens on the network, after the init-script has created the databases
	// and users, so the components can connect, as soon as it is ready.
	readinessProbe := probe(ping, probeTiming{initialDelay: 5, period: 5, failures: 3})
	readinessProbe.TimeoutSeconds = 3
	// the first start initializes the data-directory, which takes a while
	livenessProbe := probe(ping, probeTiming{initialDelay: 120, period: 20, failures: 3})
	livenessProbe.TimeoutSeconds = 5

	replicas := int32(1)
	spec := &r.Spec.MySQL
	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{Name: "mysql", Labels: appLabels("mysql")},
		Spec: appsv1.StatefulSetSpec{
			ServiceName: "mysql",
			Replicas:    &replicas,
			Selector:    &metav1.LabelSelector{MatchLabels: appLabels("mysql")},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: appLabels("mysql")},
				Spec: corev1.PodSpec{
					Affinity: r.affinity("mysql", "mysql-node"),
					Containers: []corev1.Container{{
						Name:            "mysql",
						Image:           r.Spec.MySQL.Image,
						ImagePullPolicy: r.pullPolicy(r.Spec.MySQL.ImagePullPolicy),
						Env:             env,
						Ports:           []corev1.ContainerPort{{Name: "mysql", ContainerPort: 3306}},
						VolumeMounts: []corev1.VolumeMount{
							{Name: "data", MountPath: "/var/lib/mysql"},
							{Name: "mysql-init", MountPath: "/docker-entrypoint-initdb.d", ReadOnly: true},
						},
						ReadinessProbe: readinessProbe,
						LivenessProbe:  livenessProbe,
					}},
					Volumes: []corev1.Volume{configMapVolume("mysql-init", "mysql-init")},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{
				*persistentVolumeClaim("data", r.storageClass(spec.StorageClass), spec.StorageSize),
			},
		},
	}
}
