# Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.hanami.network.mls_encryption }}
# Ed25519-key, with which hanami signs the membership-grants of the MLS-groups. All replicas of
# hanami share it.
apiVersion: v1
kind: Secret
metadata:
  name: mls-grant-signing-key
type: Opaque
data:
  mls_grant_signing_key: {{ required "secrets.mls_grant_signing_key is required, if hanami.network.mls_encryption is enabled!" .Values.secrets.mls_grant_signing_key | b64enc }}
{{- end }}
