<!--
// Copyright 2022-2026 Tobias Anker <tobias.anker@kitsunemimi.moe>

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<template>
    <div class="modal-overlay" @click.self="cancel">
        <div class="modal secret-create-modal">
            <div class="modal-topbar">
                <span>Create secret</span>
            </div>
            <div class="modal-content">
                <div>
                    <input
                        v-model="form.name"
                        type="text"
                        placeholder="Secret-Name"
                        :class="{ invalid_input: nameError }"
                    />
                    <p v-if="nameError" class="error-msg">
                        Secret-Name must be at least 4 characters
                    </p>
                </div>
                <div>
                    <div class="tab">
                        <button
                            class="tablinks"
                            :class="{ active: isSelected('generate') }"
                            @click="selectTab('generate')"
                        >
                            GENERATE
                        </button>
                        <button
                            class="tablinks"
                            :class="{ active: isSelected('manual') }"
                            @click="selectTab('manual')"
                        >
                            MANUAL
                        </button>
                    </div>
                    <div class="secret-tabcontent">
                        <div v-show="selectedTab === 'generate'">
                            <br />
                            <p>
                                The payload is generated by the omamori and
                                never leaves it in clear text.
                            </p>
                        </div>
                        <div v-show="selectedTab === 'manual'">
                            <br />
                            <input
                                v-model="form.payload"
                                type="password"
                                placeholder="Secret-Payload"
                                :class="{ invalid_input: payloadError }"
                            />
                            <p v-if="payloadError" class="error-msg">
                                Payload must be at least 8 characters
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-bottombar">
                <div class="modal-actions">
                    <button class="icon-button" @click="handleAccept">
                        <img :src="icons.acceptIcon" alt="Accept" />
                    </button>
                    <button class="icon-button" @click="cancel">
                        <img :src="icons.cancelIcon" alt="Cancel" />
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div v-if="errorPopupMsg" class="error-popup">
        <button class="error-close-btn" @click="errorPopupMsg = ''">✕</button>
        {{ errorPopupMsg }}
    </div>
</template>

<script lang="ts" setup>
import { ref, reactive } from "vue";

import { omamori } from "@/api";
import { handleAxiosError } from "@/handleAxiosError";

interface Props {
    icons: { acceptIcon: string; cancelIcon: string };
}
defineProps<Props>();
const emit = defineEmits<{
    (e: "accept"): void;
    (e: "cancel"): void;
}>();

const errorPopupMsg = ref<string>("");
const nameError = ref(false);
const payloadError = ref(false);

const form = reactive({
    name: "",
    payload: "",
});

async function handleAccept() {
    nameError.value = form.name.length < 4;
    // the payload is only typed in by the user in the manual-variant
    payloadError.value =
        selectedTab.value === "manual" && form.payload.length < 8;

    if (nameError.value || payloadError.value) {
        return;
    }

    try {
        if (selectedTab.value === "generate") {
            await omamori.generateSecret(form.name);
        } else {
            await omamori.createSecret(form.name, form.payload);
        }

        emit("accept");
    } catch (err) {
        errorPopupMsg.value = handleAxiosError(err, "Failed to create secret");
    }
}

function cancel() {
    emit("cancel");
}

//=============================================================================
// Tabs
//=============================================================================
const selectedTab = ref<"generate" | "manual">("generate");

function selectTab(tab: "generate" | "manual") {
    selectedTab.value = tab;
    payloadError.value = false;
}

function isSelected(tab: "generate" | "manual") {
    return selectedTab.value === tab;
}
</script>

<style scoped>
.secret-create-modal {
    width: 30rem;
}

.secret-tabcontent {
    margin-top: 0.5rem;
    height: 7rem;
}

/* is not found when I put this in one of the css files. Don't know why... */
.invalid_input {
    border-bottom: 2px solid #ff4d4f;
}
</style>
