CREATE TABLE virtual_machines (
    uuid VARCHAR(40) PRIMARY KEY,
    name VARCHAR(256),
    vm_state VARCHAR(16) NOT NULL DEFAULT 'RESERVED',
    number_of_cores INTEGER,
    memory_size INTEGER,
    disk_size BIGINT NOT NULL DEFAULT 5,
    image_uuid VARCHAR(40),
    public_key_uuid VARCHAR(40),
    network_uuid VARCHAR(40),
    internal_ip VARCHAR(40),
    root_disk_path VARCHAR(1024),
    seed_path VARCHAR(1024),
    tap_name VARCHAR(256),
    mac_address VARCHAR(32),
    owner_id VARCHAR(256),
    project_id VARCHAR(256),
    status VARCHAR(8),
    created_at VARCHAR(64),
    created_by VARCHAR(256),
    updated_at VARCHAR(64),
    updated_by VARCHAR(256),
    deleted_at VARCHAR(64),
    deleted_by VARCHAR(256)
);
